service: coffee-hmm-server

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'production'}
  region: ${opt:region, 'ap-northeast-2'}
  environment:
    CAFES_TABLE: ${self:service}-cafes-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.CAFES_TABLE}"

functions:
  heartbeat:
    handler: src/heartbeat.handler
    events:
      - http:
          path: /
          method: get
          cors: true
  cafeList:
    handler: src/cafe.cafeListHandler
    events:
      - http:
          path: /cafe
          method: get
          cors: true
  cafe:
    handler: src/cafe.cafeHandler
    events:
      - http:
          path: /cafe/{cafe_id}
          method: get
          cors: true

resources:
  Resources:
    DynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.CAFES_TABLE}
