service: coffee-hmm-jobs

provider:
  name: aws
  region: ${opt:region, 'ap-northeast-2'}
  runtime: nodejs12.x
  stage: ${self:custom.stage}
  memorySize: 256

resources:
  Resources:
    GenerateSitemapRole: ${file(./res/GenerateSitemapRole.yml)}
    CafeCreateSlackNotificationRole: ${file('./res/CafeCreateSlackNotificationRole.yml')}

plugins:
  - serverless-webpack

custom:
  stage: ${env:APP_STAGE, 'beta'}
  version: 0.2.0
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk
    packager: yarn
    excludeFiles: src/**/*.test.ts
  spa:
    url: https://coffeehmm.com
    s3:
      arn: arn:aws:s3:::coffee-hmm.inhibitor.com
      name: coffee-hmm.inhibitor.com
    cloudfront:
      arn: arn:aws:cloudfront::871935403311:distribution/E31ON6KII3D5OF
      distributionId: E31ON6KII3D5OF
  sqs:
    cafe:
      slackNotification:
        Fn::Join:
          - ''
          - - 'arn:aws:sqs:'
            - Ref: AWS::Region
            - ':'
            - Ref: AWS::AccountId
            - ':coffee-hmm-cafe-slack-notification-${self:custom.stage}.fifo'

functions:
  generateSitemap:
    handler: src/job/generateSitemap.handler
    role: GenerateSitemapRole
    events:
      - schedule: cron(00 13 * * ? *)
    environment:
      APP_NAME: ${self:service}
      APP_VERSION: ${self:custom.version}
      APP_STAGE: ${self:custom.stage}
      LOG_LEVEL: info
      API_SERVICE: https://${self:custom.stage}.api.coffee-hmm.inhibitor.io
      BASE_APP_URL: ${self:custom.spa.url}
      SPA_CLOUDFRONT_DISTRIBUTION_ID: ${self:custom.spa.cloudfront.distributionId}
      SPA_S3_BUCKET_NAME: ${self:custom.spa.s3.name}

  cafeCreateSlackNotification:
    handler: src/job/cafeCreateSlackNotification.handler
    role: CafeCreateSlackNotificationRole
    events:
      - sqs:
          arn: ${self:custom.sqs.cafe.slackNotification}
    environment:
      APP_NAME: ${self:service}
      APP_VERSION: ${self:custom.version}
      APP_STAGE: ${self:custom.stage}
      LOG_LEVEL: info
      API_SERVICE: https://${self:custom.stage}.api.coffee-hmm.inhibitor.io
