service: coffee-hmm-jobs

provider:
  name: aws
  region: ${opt:region, 'ap-northeast-2'}
  runtime: nodejs12.x
  stage: ${self:custom.stage}
  memorySize: 256
  role: LambdaRole

resources:
  Resources:
    LambdaRole: ${file(./res/LambdaRole.yml)}

plugins:
  - serverless-webpack

custom:
  stage: ${env:APP_STAGE, 'beta'}
  version: 0.0.1
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk
    packager: yarn
    excludeFiles: src/**/*.test.ts

functions:
  generateSitemap:
    handler: src/job/generateSitemap.handler
    events:
      - schedule: cron(30 12 * * ? *)
    environment:
      APP_NAME: ${self:service}
      APP_VERSION: ${self:custom.version}
      APP_STAGE: ${self:custom.stage}
      LOG_LEVEL: info
      API_SERVICE: https://${self:custom.stage}.api.coffee-hmm.inhibitor.io
      BASE_APP_URL: https://coffeehmm.com
      SPA_S3_BUCKET_NAME: coffee-hmm.inhibitor.com
