name: release-mobile@beta
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch"
        required: true
        default: "master"

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      WORKING_DIRECTORY: mobile_app
    defaults:
      run:
        working-directory: mobile_app
    steps:
      - name: Checkout source from branch.
        uses: actions/checkout@master
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Notify build start message.
        uses: 8398a7/action-slack@e74cd4e48f4452e8158dc4f8bcfc780ae6203364
        with:
          status: custom
          fields: commit,author,ref,workflow
          custom_payload: |
            {
              text: `Start workflow run ${process.env.AS_WORKFLOW} on ${process.env.INPUTS_BRANCH}`,
              attachments: [
                {
                  color: 'good',
                  text: `Start workflow run ${process.env.AS_WORKFLOW}\n${process.env.AS_REF}(${process.env.AS_COMMIT}) by ${process.env.AS_AUTHOR}`,
                }
              ]
            }
        env:
          INPUTS_BRANCH: ${{ github.event.inputs.branch }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
      - name: Decode signing key.
        env:
          SIGNING_KEY: ${{ secrets.ANDROID_SIGNING_KEY_BETA }}
        run: echo $SIGNING_KEY | base64 -d > android/app/keystore.jks
      - uses: actions/setup-java@4b1b3d4a82f726de9ba1945f8c6967b67caf5dcd
        with:
          distribution: adopt
          java-version: '8.0.302'
      - uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8
        with:
          flutter-version: "2.2.3"
      - name: Install flutter package dependencies.
        run: flutter pub get
      - name: Build APK.
        run: flutter build apk --release --split-per-abi --dart-define APP_STAGE=beta
        env:
          ALIAS: upload
          KEY_PATH: keystore.jks
          SIGNING_STORE_PASSWORD: ${{ secrets.ANDROID_STORE_PASSWORD_BETA }}
          SIGNING_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD_BETA }}
      - name: Pass build artifact to Slack. (arm64-v8a)
        uses: MeilCli/slack-upload-file@f8f4f6dbe44bb99b36c16a2774836022ffe56fed
        with:
          slack_token: ${{ secrets.SLACK_OAUTH_TOKEN }}
          channels: ${{ secrets.SLACK_CHANNELS }}
          file_path: ${{ env.WORKING_DIRECTORY }}/build/app/outputs/apk/release/app-arm64-v8a-release.apk
          file_name: app-arm64-v8a-release.apk
          file_type: apk
      - name: Pass build artifact to Slack. (armeabi-v7a)
        uses: MeilCli/slack-upload-file@f8f4f6dbe44bb99b36c16a2774836022ffe56fed
        with:
          slack_token: ${{ secrets.SLACK_OAUTH_TOKEN }}
          channels: ${{ secrets.SLACK_CHANNELS }}
          file_path: ${{ env.WORKING_DIRECTORY }}/build/app/outputs/apk/release/app-armeabi-v7a-release.apk
          file_name: app-armeabi-v7a-release.apk
          file_type: apk
      - name: Pass build artifact to Slack. (x86_64)
        uses: MeilCli/slack-upload-file@f8f4f6dbe44bb99b36c16a2774836022ffe56fed
        with:
          slack_token: ${{ secrets.SLACK_OAUTH_TOKEN }}
          channels: ${{ secrets.SLACK_CHANNELS }}
          file_path: ${{ env.WORKING_DIRECTORY }}/build/app/outputs/apk/release/app-x86_64-release.apk
          file_name: app-x86_64-release.apk
          file_type: apk
      - name: Notify build message.
        uses: 8398a7/action-slack@e74cd4e48f4452e8158dc4f8bcfc780ae6203364
        with:
          status: ${{ job.status }}
          fields: repo,action,ref,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        if: always()
