name: coverage
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - dev/server
defaults:
  run:
    shell: bash
jobs:
  check-lint:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: services/http-api
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12"
      - name: Install dependencies.
        run: make deps
      - name: Generate type coverage report.
        run: make typecheck-report
      - name: Upload coverage to codecov.
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          files: services/http-api/coverage/type-coverage.json
          flags: services/http-api
