name: release-server
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    stpes:
      - uses: actions/checkout@master
      - uses: actions/npm@master
        with:
          args: install
      - uses: serverless/github-action@master
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.SERVERLESS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SERVERLESS_AWS_SECRET_ACCESS_KEY }}
