name: release-app
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
      - run: yarn install
      - run: yarn build
      - run: ls build/
